<<<<<<< HEAD
url: https://Hatinilab.github.io
baseurl: /agency-jekyll-theme/
=======
url: http://hatinilab.github.io
baseurl: /
>>>>>>> 46b22f2363dc712ef7a86c010677d894d7c042d9

# Site settings
title: Hatini Lab
email: your-email@domain.com
description: "Hatini lab seeks to elucidate the molecular and cellular basis of epithelial tissue morphogenesis to better understand basic mechanisms of animal development."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Victor Hatini
  pic: 1
  position: Lab PI
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Rodrigo Cilla
  pic: 2
  position: Postdoctoral Researcher
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
